// mutation 常量
export const SET_ARTIST = 'SET_ARTIST'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_RECOMMEND_ITEM = 'SET_RECOMMEND_ITEM'

export const SET_SELECTED_TOP_LIST = 'SET_SELECTED_TOP_LIST'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'
